# Generated by Django 2.2.12 on 2021-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20201121_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=300)),
                ('price', models.CharField(help_text='Price', max_length=300)),
                ('url', models.URLField(help_text='Url', max_length=1000)),
                ('img_url', models.URLField(blank=True, default='default.png', help_text='Image Url', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, help_text='Color', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_url',
            field=models.URLField(blank=True, default='default.png', help_text='Image Url', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, help_text='size', max_length=300, null=True),
        ),
    ]
