# Generated by Django 2.2.12 on 2021-08-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20210816_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazon',
            unique_together={('title', 'price', 'url', 'img_url')},
        ),
    ]
